import { NeatGradient } from "@firecms/neat";

const config = {
    colors: [
        {
            color: '#800E12',
            enabled: true,
        },
        {
            color: '#F8F1E7',
            enabled: true,
        },
        {
            color: '#F07121',
            enabled: true,
        },
        {
            color: '#AA1F24',
            enabled: true,
        },
        {
            color: '#F8F1E7',
            enabled: true,
        },
        {
            color: '#AA1F24',
            enabled: true,
        },
    ],
    speed: 3.5,
    horizontalPressure: 1,
    verticalPressure: 4,
    waveFrequencyX: 5,
    waveFrequencyY: 2,
    waveAmplitude: 1,
    shadows: 0,
    highlights: 2,
    colorBrightness: 0.85,
    colorSaturation: 6,
    wireframe: false,
    colorBlending: 7,
    backgroundColor: '#000000',
    backgroundAlpha: 1,
    grainScale: 0,
    grainSparsity: 0,
    grainIntensity: 0.35,
    grainSpeed: 1,
    resolution: 0.3,
    yOffset: -6883.5,
    yOffsetWaveMultiplier: 5.7,
    yOffsetColorMultiplier: 7.6,
    yOffsetFlowMultiplier: 12,
    flowDistortionA: 5,
    flowDistortionB: 0.5,
    flowScale: 3.3,
    flowEase: 1,
    flowEnabled: true,
    enableProceduralTexture: false,
    textureVoidLikelihood: 0.27,
    textureVoidWidthMin: 60,
    textureVoidWidthMax: 420,
    textureBandDensity: 1.2,
    textureColorBlending: 0.06,
    textureSeed: 333,
    textureEase: 0.5,
    proceduralBackgroundColor: '#0E0707',
    textureShapeTriangles: 20,
    textureShapeCircles: 15,
    textureShapeBars: 15,
    textureShapeSquiggles: 10,
    domainWarpEnabled: true,
    domainWarpIntensity: 0,
    domainWarpScale: 2.9,
    vignetteIntensity: 0,
    vignetteRadius: 0.8,
    fresnelEnabled: false,
    fresnelPower: 3.3,
    fresnelIntensity: 0.3,
    fresnelColor: '#FFFFFF',
    iridescenceEnabled: false,
    iridescenceIntensity: 0.5,
    iridescenceSpeed: 1,
    bloomIntensity: 0,
    bloomThreshold: 0.65,
    chromaticAberration: 0,
};

const gradient = new NeatGradient({
    ref: document.getElementById("gradient"),
    ...config
});